### ISSUE TITLE
Feedback: Policy - Coding

### ISSUE THREAD

**Issue by datawookie** [datawookie/www-exegetic-biz#40]
Hey @marinuslouw,

Great work on this so far.

Here's some feedback.

## Markdown

I thought that it would be pertinent to have a markdown section too. The first item that I suggest you put into that section is "Always insert an open line between a section heading and the section content." Then go and apply this principle across the document. :)

## General

- In the Architecture section the, "Before you start..." should not be part of the list.
- Define "hard-coding".
- I'd suggest creating a separate sub-section called "Naming Things" and moving all related content into it (this applies across all languages).

## R

- Line length is arbitrary. I'm in favour of 120 characters.
- Headers should be divided into two sections: file headers and section headers. Your example is a section header. We should also mention what goes into the file header.
- Some of the points in the Comments section could go into the corresponding section under General.
- Your example comment seems to illustrate the what and not the why.
- File names should go into "Naming Things" section (exception is anything that is R-specific).
- Sample applies to the Object names section (exception is anything that is R-specific).

## Python

- Line length: I think we should just have a single section on this under General. Line length should be the same across languages.
- Source file encoding: could probably also go in General and I think that we can probably just say UTF-8 throughout.
- Headers could also probably go into General (along with the corresponding stuff from R).
- Comments should be handled in General.
- All of the naming stuff can go into General (exception is anything that is Python-specific).

## SQL

- Since SQL comments are different from Python and R it would make sense to have a separate section for them.
- "Avoid object-oriented design principles..." seems to be a double negative. Is this really necessary? Seems pretty niche.
- Line spacing: first line should not be part of list; don't use capitals to start list items.

Please apply these changes and then do your own editing for the second round.

Also ask @gerrywalsh to take a look at this and offer to take a look at the documents that he has been working on.

**Comment by ghost** [comment]
Great thanks.

Will do.
