### ISSUE TITLE
Feedback: Coding standards

### ISSUE THREAD

**Issue by MeganBeckett** [datawookie/www-exegetic-biz#48]
- Insert a table of contents otherwise it's not very clear from scrolling through the doc, at least so you can jump to R/python/SQL for example

## General
- Is General a level 1 heading? If so, start with this before Markdown? 
- Hard-coding: I'm not sure what this line is?
verb COMPUTING fix (data or parameters) in a program in such a way that they cannot be altered without modifying the program.
A definition? If so, it reads weirdly - perhaps say it's a definition or just define it in a sentence.

## R
- Please include how to format pipes in the tidyverse. This is very important and we really must enforce this for legibility (ie. each step on a new line, etc). Also we generally do variable name and assignment on the same line, and then steps below (rather than assignment at the end of a pipe).

## SQL
- Spaces and line spacing - is this really how we are doing it? ie. creating this "river" down the middle? I haven't seen this much anywhere in our code so far.
- This is one convention - are we saying this is what we want to adopt? I'm not sure.
- So far, what i think we have been doing is to have the commands left aligned?
- Also, why is the following in brackets?
```
(SELECT f.species_name,
        AVG(f.height) AS average_height, AVG(f.diameter) AS average_diameter
   FROM flora AS f
  WHERE f.species_name = 'Banksia'
     OR f.species_name = 'Sheoak'
     OR f.species_name = 'Wattle'
  GROUP BY f.species_name, f.observation_date)
```
- And, I would much rather say you have each SELECT column on a new line for legibility, like this:
```
SELECT
  name,
  projects,
  country,
  COUNT(users_id) AS users_count
FROM ...
```
- Personally, I think the indentation for joins is weird and makes it harder to read. Is this the coding style you have adopted elsewhere for SQL in Exegetic projects?
- And, normally also indent before AND and OR, not just a new line?
- See how it's explained here: https://docs.telemetry.mozilla.org/concepts/sql_style.html#left-align-root-keywords

**Comment by datawookie** [comment]
Thanks, @MeganBeckett. I'm going to assign this to @marinuslouw.

**Comment by Axiematic** [comment]
@marinuslouw since this has been handled please can you close this issue.

**Comment by datawookie** [comment]
Actually, no, it looks like at least *some* of @MeganBeckett's comment have not been actioned. @marinuslouw please handle all of @MeganBeckett's feedback immediately. I was under the impression that this document had been finalised a long time ago... Please sort this out! Thanks!

**Comment by ghost** [comment]
@datawookie I had a look at this again now, and I can't find anything on Megan's reply that I didn't implement?

**Comment by datawookie** [comment]
When I looked there were multiple reference to the "river", which @MeganBeckett suggested (and I agree entirely) is not the way that we write SQL.

**Comment by datawookie** [comment]
Sorry, I was looking at the wrong branch. @marinuslouw you're in the clear. I'm being a twat. Please create a PR against `dev`.

**Comment by ghost** [comment]
No problem at all. Will do.
